### ISSUE TITLE
name vs title

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/alternate-assets#10]
Currently, the alternate asset extension defines title and description. I think this is not ideal, due to the reasone below:

Here's an example that I've seen in the wild:
```json
{
      "href": "https://example.com/example.tif",
      "type": "image/jp2",
      "file:size": 100015921,
      "file:checksum": "1620a7e5018b93dd4c9b99b379215b6fe924466829154c821c0044ceb6a304dedc61",
      "title": "Green (band 3) - 10m",
      "alternate": {
        "s3": {
          "href": "s3://example.com/example.tif",
          "storage:platform": "OTHER",
          "storage:region": "waw",
          "storage:requester_pays": false,
          "storage:tier": "hot"
        } 
      }
    }
```

The title in the overall asset is a generic title for the file and looks fine. Providing the title again in the sub-asset doesn't make a lot of sense though, it would be the same, just hosted on S3.

STAC Browser implements this extension as a Tab interface. Showing the titles for the tabs doesn't make sense. I've implemented it as such, that it supports a `name` field to provide short labels for the tab headers.

I'd actually propose to add a name field for such cases to the Alternate Asset Object.

title and description I'd remove and refer back to common metadata, saying that extensions and common metadata fields such as title and description can be used to further define the alternative asset.

The updates example would look like this:
```json
{
      "href": "https://example.com/example.tif",
      "type": "image/jp2",
       "name": "HTTP",
      "file:size": 100015921,
      "file:checksum": "1620a7e5018b93dd4c9b99b379215b6fe924466829154c821c0044ceb6a304dedc61",
      "title": "Green (band 3) - 10m",
      "alternate": {
        "s3": {
          "href": "s3://example.com/example.tif",
          "name": "S3",
          "storage:platform": "OTHER",
          "storage:region": "waw",
          "storage:requester_pays": false,
          "storage:tier": "hot"
        } 
      }
    }
```

and render as such:
![altassets](https://github.com/stac-extensions/alternate-assets/assets/8262166/bf1ba378-6bdd-4505-817f-3dcba01148ea)

See also: https://github.com/radiantearth/stac-browser/commit/47dea4f23968c2bfdb7c3642725c4879b227af35

**Comment by matthewhanson** [comment]
I'm +1 on all this - dropping title and description and just using 'name' from common metadata.

**Comment by m-mohr** [comment]
I'll create PR, @matthewhanson to review.

**Comment by matthewhanson** [comment]
Reconsidering this - there is already a key used in the alternate dictionary, in this case "s3".   Having a name is a bit redundant, but if there is a name then Best Practices should state that the key and name should be the same.

**Comment by m-mohr** [comment]
Hmm, I don't think I agree. Name for me is human readable with spaces, special characters, and might be localized (language extension). A key should be stable and machine-optimized. Usually, I'd put the name in a title, but it's ambiguous with the main asset title, which describes the title for the asset and usually also applies without change to the alternate asset. 

Example:

Name (English localization of an Item: "Local filesystem"
Name (German localization of an Item): "Lokales Dateisystem"
Asset key: "local"

You don't want to change the asset key when you change languages in a single catalog, don't you?
