### ISSUE TITLE
Clarify what an alternate asset is

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/alternate-assets#13]
What is an alternate asset? What is allowed?
- Different location, needs the same checksum (I assume that, needs to be clarfied)
- Different resolution files? (Sentinel-2 red band 10m vs. 20m)
- Different files type? (PNG/COG/JPEG2000/...)

**Comment by matthewhanson** [comment]
Alternate URLs would have been a better name. The original idea was that it was the exact same underlying file (so yes same checksum), but could be a copy in another location, or even just a different URL that ultimately points to the same asset.   The most common example of this is in USGS's Landsat API where they have an https URL that requires authentication and they have control over bandwidth (and thus egress charges) and it's free.  But then they also have an alternate s3 URL which allows direct access via a requester pays bucket.  

https://landsatlook.usgs.gov/stac-server/collections/landsat-c2l2-sr/items/LC09_L2SR_081076_20240324_20240325_02_T1_SR

**Comment by m-mohr** [comment]
Okay, we should clarify that. I think checksum is a good indicator.
