### ISSUE TITLE
"alternate" vs "alternative"

### ISSUE THREAD

**Issue by felix-schott** [stac-extensions/alternate-assets#9]
Hi, I think it's a bit unfortunate that this extension uses the word "alternate" to describe a different location one can choose to access data from. "alternative" is more widely understood to describe choice between options - "alternate" is an Americanism and it might even be considered incorrect to use "alternate" to describe choice rather than substitution in the US.

Using "alternate" in this context seems to be a chiefly American thing, while British English (and I believe Australian English and other English varieties) would use "alternative". For BE speakers, "alternate" means ["to happen or exist one after the other repeatedly" or "every other"](https://dictionary.cambridge.org/dictionary/english/alternate). By no means it is better to prioritise BE over AE but I'd argue that "alternative" would be more universally understood by the global English language community to express choice between options as AE also knows and uses "alternative" at least as a noun in this context (as an adjective, "alternate" might be preferred over "alternative" in the US?). It is noteworthy however that the Grammarist, writing from an AE POV, maintains that ["[a]n alternate is something or someone that serves in place of another. An alternative is a second option that does not replace the first."](https://grammarist.com/usage/alternate-alternative/) - in which case "alternate" would be considered incorrect even in the US since we're talking about choice here (the article goes on to state that the corresponding adjectives have the same difference in meaning).

I know this is nitpicky and I'm not saying "alternative" is clearly preferable over "alternate" or that a somewhat established STAC extension should be changed now. But maybe take this comment as a suggestion to be mindful of such differences for future extensions. STAC is not an American extension but to be used by a global community that speak different varieties of English as their first or second language. Additionally, I'm not even sure if "alternate" would be appropriate to use in formal AE. Maybe it's just me but as someone more familiar with BE I wasn't even aware "alternate" could mean "alternative" in the US and not just "every other".

Additional sources:
- [Cambridge Dictionary alternative](https://dictionary.cambridge.org/dictionary/english/alternative)/[alternate](https://dictionary.cambridge.org/dictionary/english/alternate)
- [Collins Dictionary: What is the difference between alternate and alternative](https://grammar.collinsdictionary.com/english-usage/what-is-the-difference-between-alternate-and-alternative)

**Comment by m-mohr** [comment]
I agree that alternative is likely easier to understand. Unfortunately, the IANA relation type is also called "alternate" and it is used throughout multiple extensions and specifications now so it's unlikely a switch to "alternative" is viable.
